### ISSUE TITLE
Setting page level custom targeting instead of slot level targetings

### ISSUE THREAD

**Issue by ray1028** [tomattone/react-ad-manager#1]
We should set the slot level custom targeting instead of page level targeting. This will cause an issue when there are multiple ads on a single page that needs different custom targetings
<img width="666" alt="image" src="https://user-images.githubusercontent.com/48531371/236949974-b88dcedf-22bd-4746-a504-ca21a55b947c.png">

**Comment by tomattone** [comment]
Good! I didn't really notice it.

**Comment by ray1028** [comment]
Hey thanks for your quick respond. can you publish it to NPM I'm using the downstream for a project?
